services:
  # PostgreSQL Service
  api-db:
    image: postgres:16
    container_name: api-db
    tty: true
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: postgresql
    volumes:
      - api-dbdata:/var/lib/postgresql/data
    networks:
      - api-app-network

  # PHP Service (Laravel App)
  api-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-app
    user: www-api
    container_name: api-app
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - api-app-network

  # Nginx Web Server
  api-webserver:
    image: nginx:alpine
    container_name: api-webserver
    tty: true
    ports:
      - "8008:8006"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-app
    networks:
      - api-app-network

# Define Networks
networks:
  api-app-network:
    driver: bridge

# Define Volumes
volumes:
  api-dbdata:
    driver: local
  api-redis-data:
    driver: local
